### ISSUE TITLE
Update logo to Pluto

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/pluto#28]
The colors surrounds the 3 letters in the middle `R[E][D][O]X`. If we change to Pluto we get `P[L][U][T]O`.

**Comment by Haggus** [comment]
I will update the logo for now. However, since we changed the name, I'm thinking about layout redesign.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/pluto/pull/29.

I'm curious about the redesign!
